pipeline {
    agent any
    stages {
        
        stage('Staging'){
            steps{
                echo 'Starting staging job'
                build job: 'PIPELINE-FULL-STAGING', parameters: [
                      string(name:'ENVIRONMENT', value: "staging")]
            }
        }
        stage('Merge'){
            steps{
                withCredentials([string(credentialsId: 'github-charlotron-token', variable: 'GIT_TOKEN')]) { 
                    sh script: """
                        set -x

                        git remote set-url origin \$(git remote -v | grep push | awk '{print \$2}' | perl -pe 's/:\\/\\//:\\/\\/$GIT_TOKEN@/g')
                        git remote -v

                        git branch -a
                        git checkout -b develop origin/develop
                        git checkout -b master origin/master
                        git merge develop
                        git push origin master
                    """, label: "Merging code to master"
                }
            }
        }
        stage('Production'){
            steps{
                
                echo 'Starting production job'
                build job: 'PIPELINE-FULL-PRODUCTION', parameters: [
                      string(name:'ENVIRONMENT', value: "production")]
            }
        }
    }
    post { 
        always { 
            echo 'Clean env: delete dir'
            cleanWs()
        }
    }
}